-- =============================================================================
-- Mio Kisaragi Jazz — live SELECT-only CONTENT seed — TEMPLATE
-- Phase: cms-core-v2-mio-supabase-live-select-only-seed-write-gate
-- Status: DO NOT EXECUTE without explicit write approval
-- Staging only: kmjqppxjdnwwrtaeqjta
-- STOP production: vsbvndwuajjhnzpohghh
-- site_slug: mio-kisaragi-jazz ONLY
-- Source: fixtures/mio-kisaragi-jazz-data/
--
-- GATE BLOCKER (2026-08-01):
--   schedules.date is NOT NULL on staging, but fixture row
--   mio-sched-2026-09-01 has date=null (TBD / 日付未定).
--   Option A success requires schedules total=16 / published=14.
--   Until TBD is resolved (approved sentinel date OR fixture/schema change),
--   block B ends with RAISE → full transaction ROLLBACK (no partial seed).
--   READY_FOR_MIO_SEED_APPLY: false
--
-- Safety:
--   - plain INSERT only (no upsert overwrite)
--   - collision guard: abort if any mio content/sites row exists
--   - single transaction
--   - no table wipe / broad DELETE in seed path
--   - anon/SQL-editor operator only · no privileged keys / secrets in this file
-- Regenerated by: scripts/generate-mio-kisaragi-jazz-live-select-seed-sql.mjs
-- =============================================================================

-- #############################################################################
-- A) WRITE直前 SELECT-only preflight（copy/paste · 実行可 · writeなし）
-- #############################################################################

select current_database() as db_name;

-- Expect all mio content/sites counts = 0 before seed.
select * from (
  select 'sites'::text as bucket, count(*)::int as n from public.sites where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'schedules', count(*)::int from public.schedules where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'schedules_published', count(*)::int from public.schedules where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'discography', count(*)::int from public.discography where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography_published', count(*)::int from public.discography where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'discography_tracks', count(*)::int from public.discography_tracks where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography_tracks_on_published_releases', count(*)::int
    from public.discography_tracks t
    join public.discography d on d.legacy_id = t.discography_legacy_id and d.site_slug = t.site_slug
   where t.site_slug = 'mio-kisaragi-jazz' and d.published = true
  union all
  select 'site_embeds', count(*)::int from public.site_embeds where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'site_embeds_published', count(*)::int from public.site_embeds where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'site_page_fields', count(*)::int from public.site_page_fields where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'about_profile_lede_published', count(*)::int from public.site_page_fields
   where site_slug = 'mio-kisaragi-jazz' and page_key = 'about' and field_key = 'profile.lede' and published = true
) s order by bucket;

-- Gosaki isolation sanity (must remain unchanged by Mio seed).
select 'gosaki_schedules_published' as bucket, count(*)::int as n
  from public.schedules where site_slug = 'gosaki-piano' and published = true;

-- #############################################################################
-- B) Seed SQL（単一transaction · 現状は最終assertで必ずROLLBACK）
--    DO NOT EXECUTE without approval. Production ref STOP.
-- #############################################################################

begin;

-- B1) Collision guard — any existing Mio row aborts (no overwrite).
do $$
declare
  v_sites int;
  v_sched int;
  v_disco int;
  v_tracks int;
  v_embeds int;
  v_fields int;
begin
  select count(*)::int into v_sites from public.sites where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_sched from public.schedules where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_disco from public.discography where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_tracks from public.discography_tracks where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_embeds from public.site_embeds where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_fields from public.site_page_fields where site_slug = 'mio-kisaragi-jazz';
  if v_sites <> 0 or v_sched <> 0 or v_disco <> 0 or v_tracks <> 0 or v_embeds <> 0 or v_fields <> 0 then
    raise exception 'STOP collision: mio-kisaragi-jazz rows already exist (sites=%, schedules=%, discography=%, tracks=%, embeds=%, page_fields=%). Refuse overwrite.',
      v_sites, v_sched, v_disco, v_tracks, v_embeds, v_fields;
  end if;
end $$;

-- B2) sites (plain INSERT)
insert into public.sites (site_slug, display_name, status)
values ('mio-kisaragi-jazz', 'Mio Kisaragi Jazz', 'active');

-- B3) schedules — dated rows only (15). TBD row excluded (date NOT NULL blocker).
insert into public.schedules (
  legacy_id, site_slug, date, year, month, title, venue,
  open_time, start_time, price, description, image_url,
  source_file, source_route, show_on_home, home_order, published, sort_order
) values
  ('mio-sched-2026-08-01', 'mio-kisaragi-jazz', '2026-08-07', 2026, '2026-08', 'Blue Lantern Duo — Early Set', 'Harbor Note Club（架空）', '17:30', '18:00', '¥4,000（1ドリンク別）', '出演: 如月澪 (vo) / 青葉蓮 (pf)
予約: https://example.invalid/reserve/mio-0807-early', 'images/event-placeholder.svg', 'schedule-2026-08.html', '/schedule/2026-08/', true, 1, true, 10),
  ('mio-sched-2026-08-02', 'mio-kisaragi-jazz', '2026-08-12', 2026, '2026-08', '水路沿いの無料サンデー・アフタヌーン（平日振替）', 'Canal Side Gallery（架空）', '14:00', '14:30', '無料', '出演: 如月澪 (vo) / 南梢 (ds)
入場無料 · 予約不要', null, 'schedule-2026-08.html', '/schedule/2026-08/', false, null, true, 20),
  ('mio-sched-2026-08-03', 'mio-kisaragi-jazz', '2026-08-21', 2026, '2026-08', 'Quiet Standards Night', 'Amber Cup Jazz Room（架空）', '19:00', '19:30', '', '出演: 如月澪 (vo) / 青葉蓮 (pf)
料金未定 · チャージ後日発表', null, 'schedule-2026-08.html', '/schedule/2026-08/', false, null, true, 30),
  ('mio-sched-2026-08-04a', 'mio-kisaragi-jazz', '2026-08-07', 2026, '2026-08', 'Blue Lantern Duo — Late Set', 'Harbor Note Club（架空）', '20:30', '21:00', '¥4,500（1ドリンク別）', '出演: 如月澪 (vo) / 青葉蓮 (pf) / 黒瀬透 (b)
予約: https://example.invalid/reserve/mio-0807-late
同日昼夜2公演の夜公演。', 'images/event-placeholder.svg', 'schedule-2026-08.html', '/schedule/2026-08/', true, 2, true, 11),
  ('mio-sched-2026-08-04b', 'mio-kisaragi-jazz', '2026-09-03', 2026, '2026-09', 'September Warm-up — Early', 'Silver Shelf Bar（架空）', '17:00', '17:30', '¥3,500', '出演: 如月澪 / 青葉蓮
予約: https://example.invalid/reserve/mio-0903-e
9月昼夜2公演の昼。', 'images/event-placeholder.svg', 'schedule-2026-09.html', '/schedule/2026-09/', false, null, true, 10),
  ('mio-sched-2026-08-05', 'mio-kisaragi-jazz', '2026-09-03', 2026, '2026-09', 'September Warm-up — Late', 'Silver Shelf Bar（架空）', '20:00', '20:30', '¥3,800', '出演: 如月澪 / 青葉蓮 / 黒瀬透
同日夜。予約URLなし。複数出演者。', 'images/event-placeholder.svg', 'schedule-2026-09.html', '/schedule/2026-09/', false, null, true, 11),
  ('mio-sched-2026-08-06', 'mio-kisaragi-jazz', '2026-08-28', 2026, '2026-08', 'Paper Lanterns 全曲ナイト', 'North Window Club（架空）', '18:45', '19:15', '¥5,500（1ドリンク込）', '出演: 如月澪 / 青葉蓮 / 黒瀬透 / 南梢
住所: 架空市港区ランタン通り1-2-3
会場website: https://example.invalid/venues/north-window
予約: https://example.invalid/reserve/mio-0828', 'images/event-placeholder.svg', 'schedule-2026-08.html', '/schedule/2026-08/', false, null, true, 40),
  ('mio-sched-2026-08-07', 'mio-kisaragi-jazz', '2026-08-15', 2026, '2026-08', '真夏のバラード夜会 — ゲスト多数のロングタイトルでレイアウトを試す特別公演（字幕付きトークあり）', 'Moonrail Hall（架空）', '18:00', '18:30', '料金未定', '出演: 如月澪 / 青葉蓮 / 黒瀬透 / 南梢 / ゲスト: 架空サックス奏者
予約: https://example.invalid/reserve/mio-0815', 'images/event-placeholder.svg', 'schedule-2026-08.html', '/schedule/2026-08/', true, 3, true, 25),
  ('mio-sched-2026-07-20', 'mio-kisaragi-jazz', '2026-07-20', 2026, '2026-07', '真夏前夜のスタンダード（過去公演・公開残置）', 'Leaf Studio Annex（架空）', '19:00', '19:30', '¥3,000', '出演: 如月澪
過去の公開公演。月ページに残すケース。', null, null, '/schedule/2026-07/', false, null, true, 10),
  ('mio-sched-2026-08-10', 'mio-kisaragi-jazz', '2026-08-03', 2026, '2026-08', 'Private rehearsal (draft — not public)', 'Studio North（架空）', '13:00', '13:30', null, '非公開リハーサル。HTMLコメント / fixture-meta と対応。', null, null, null, false, null, false, 1),
  ('mio-sched-2026-08-11', 'mio-kisaragi-jazz', '2026-09-20', 2026, '2026-09', 'Venue hold pending (not public)', 'TBD Club（架空）', null, null, null, '仮押さえ。Core に pending enum がないため published=false + extension で表現。', null, null, null, false, null, false, 2),
  ('mio-sched-2026-08-12', 'mio-kisaragi-jazz', '2026-08-30', 2026, '2026-08', '昼のヴォーカル・レッスン公開実演', 'Leaf Studio Annex（架空）', '13:00', '13:20', '¥2,000', '出演: 如月澪
画像なし・予約なし。', null, 'schedule-2026-08.html', '/schedule/2026-08/', false, null, true, 50),
  ('mio-sched-2026-09-15', 'mio-kisaragi-jazz', '2026-09-27', 2026, '2026-09', '季末トリオ — 長いサブタイトル付きのフィナーレ公演でカード幅を確認する', 'Copper Rail Theater（架空）', '16:00', '16:30', '¥5,000（1ドリンク込）', '出演: 如月澪 / 青葉蓮 / 黒瀬透 / 南梢
予約: https://example.invalid/reserve/mio-0927
月またぎハブ用の9月代表公演。', 'images/event-placeholder.svg', 'schedule-2026-09.html', '/schedule/2026-09/', false, null, true, 40),
  ('mio-sched-2026-08-15', 'mio-kisaragi-jazz', '2026-09-14', 2026, '2026-09', 'Guest Night: Voices Across the River', 'Riverbend Loft（架空）', '18:30', '19:00', '¥6,000（ドリンク別）', '出演: 如月澪 / 架空ゲストボーカルA / 青葉蓮 / 南梢
予約専用URLのみ: https://example.invalid/reserve/mio-0914', 'images/event-placeholder.svg', 'schedule-2026-09.html', '/schedule/2026-09/', false, null, true, 20),
  ('mio-sched-2026-08-16', 'mio-kisaragi-jazz', '2026-09-22', 2026, '2026-09', 'Standards for Rainy Windows', 'Umbrella Cellar（架空）', '19:00', '19:40', '¥4,200', '出演: 如月澪 / 黒瀬透
画像なし・予約なし。Home upcoming 候補としても利用可。', null, 'schedule-2026-09.html', '/schedule/2026-09/', true, 4, true, 30);

-- TBD fixture row NOT inserted (date=null vs schedules.date NOT NULL):
--   legacy_id=mio-sched-2026-09-01 published=true month=2026-09

-- B4) discography releases (5)
insert into public.discography (
  legacy_id, site_slug, title, artist, label, catalog_number,
  purchase_url, streaming_url, release_date, description, cover_image_url,
  sort_order, published
) values
  ('mio-disco-album-01', 'mio-kisaragi-jazz', 'Paper Lanterns', 'Mio Kisaragi', 'Fictional Room Records', 'FRR-001', 'https://example.invalid/buy/paper-lanterns', 'https://example.invalid/stream/paper-lanterns', '2025-11-02', '夜の室内楽とボーカルのための架空フルアルバム。', 'images/album-placeholder.svg', 10, true),
  ('mio-disco-album-02', 'mio-kisaragi-jazz', 'Two Songs for Late Trains', 'Mio Kisaragi', 'Fictional Room Records', 'FRR-002', 'https://example.invalid/buy/two-songs', null, '2024-06-18', 'track 少数のシングル。配信なし・購入リンクのみ。', 'images/album-placeholder.svg', 20, true),
  ('mio-disco-single-01', 'mio-kisaragi-jazz', 'Harbor Sketch (teaser single)', 'Mio Kisaragi', null, null, null, 'https://example.invalid/stream/harbor-sketch', '2024-01-10', '1 track · streaming only。', 'images/album-placeholder.svg', 30, true),
  ('mio-disco-album-03', 'mio-kisaragi-jazz', 'Harbor Sketch (EP announcement card)', 'Mio Kisaragi', 'Fictional Room Records', null, null, null, null, 'トラック情報なし・ジャケット画像なし・配信リンクなし・発売日不明。Credits: Produced by fictional producer H. Nori. Recorded at Imaginary Room Studio. Mixed by A. Kabe. Mastered by L. Tone. Artwork concept by Studio Fable. Special thanks to Harbor Note Club staff and volunteer listeners. Additional liner notes reserved for CMS long-credit layout tests.', null, 40, true),
  ('mio-disco-live-01', 'mio-kisaragi-jazz', 'Basement Tape Vol.0 (unreleased)', 'Mio Kisaragi', null, null, null, null, null, '未公開セッション。公開期待値から除外。fixture-meta rel-unreleased-session-tape と対応。', null, 90, false);

-- B5) discography_tracks (14) — always set site_slug; no duration/release_id columns
insert into public.discography_tracks (
  discography_legacy_id, track_number, title, sort_order, site_slug
) values
  ('mio-disco-album-01', 1, 'Opening Curtain', 1, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 2, 'Mist Over Sumida', 2, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 3, 'Blue Ticket', 3, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 4, 'Quiet Platform', 4, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 5, 'Paper Lanterns', 5, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 6, 'Guest Chair', 6, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 7, 'Midnight Transfer', 7, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 8, 'Rain on the Awning', 8, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 9, 'Last Call Waltz', 9, 'mio-kisaragi-jazz'),
  ('mio-disco-album-01', 10, 'Closing Light', 10, 'mio-kisaragi-jazz'),
  ('mio-disco-album-02', 1, 'Late Train Home', 1, 'mio-kisaragi-jazz'),
  ('mio-disco-album-02', 2, 'Platform Lullaby', 2, 'mio-kisaragi-jazz'),
  ('mio-disco-single-01', 1, 'Harbor Sketch', 1, 'mio-kisaragi-jazz'),
  ('mio-disco-live-01', 1, 'Warm-up Hum (unreleased)', 1, 'mio-kisaragi-jazz');

-- B6) site_embeds (6) — unparseable shorts/invalid use example.invalid embed_url (NOT NULL)
insert into public.site_embeds (
  site_id, site_slug, provider, legacy_item_id, title,
  source_url, embed_url, published, sort_order
)
select
  s.id,
  s.site_slug,
  v.provider,
  v.legacy_item_id,
  v.title,
  v.source_url,
  v.embed_url,
  v.published,
  v.sort_order
from public.sites s
cross join (
  values
    ('youtube', 'mio-yt-01', 'Mist Over Sumida (live clip)', 'https://www.youtube.com/watch?v=mioWatch001', 'https://www.youtube-nocookie.com/embed/mioWatch001', true, 10),
    ('youtube', 'mio-yt-02', 'Soundcheck vignette', 'https://youtu.be/mioYtBe0001', 'https://www.youtube-nocookie.com/embed/mioYtBe0001', true, 20),
    ('youtube', 'mio-yt-03', 'Paper Lanterns — studio teaser', 'https://www.youtube.com/embed/mioEmbed001', 'https://www.youtube-nocookie.com/embed/mioEmbed001', true, 30),
    ('youtube', 'mio-yt-04', '30-second brush intro', 'https://www.youtube.com/shorts/mioShort001', 'https://example.invalid/mio-fail-closed-embed', true, 40),
    ('youtube', 'mio-yt-05', 'Unlisted session (not public)', 'https://www.youtube.com/watch?v=mioHidden01', 'https://www.youtube-nocookie.com/embed/mioHidden01', false, 50),
    ('youtube', 'mio-yt-06', 'Malformed URL item', 'not-a-youtube-url', 'https://example.invalid/mio-fail-closed-embed', true, 60)
) as v(provider, legacy_item_id, title, source_url, embed_url, published, sort_order)
where s.site_slug = 'mio-kisaragi-jazz';

-- B7) site_page_fields — about / profile.lede (1)
insert into public.site_page_fields (
  site_id, site_slug, page_key, field_key, value_text, published, sort_order
)
select
  s.id,
  s.site_slug,
  'about',
  'profile.lede',
  '小さなクラブの灯りを好む架空のボーカリスト。言葉の間と息の長さを大切に歌います。',
  true,
  10
from public.sites s
where s.site_slug = 'mio-kisaragi-jazz';

-- B8) Option A success assert — FAILS until TBD schedule date resolved (forces ROLLBACK).
do $$
declare
  v_sites int;
  v_sched int;
  v_sched_pub int;
  v_disco int;
  v_disco_pub int;
  v_tracks int;
  v_tracks_pub_parent int;
  v_embeds int;
  v_embeds_pub int;
  v_lede int;
begin
  select count(*)::int into v_sites from public.sites where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_sched from public.schedules where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_sched_pub from public.schedules where site_slug = 'mio-kisaragi-jazz' and published = true;
  select count(*)::int into v_disco from public.discography where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_disco_pub from public.discography where site_slug = 'mio-kisaragi-jazz' and published = true;
  select count(*)::int into v_tracks from public.discography_tracks where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_tracks_pub_parent
    from public.discography_tracks t
    join public.discography d on d.legacy_id = t.discography_legacy_id and d.site_slug = t.site_slug
   where t.site_slug = 'mio-kisaragi-jazz' and d.published = true;
  select count(*)::int into v_embeds from public.site_embeds where site_slug = 'mio-kisaragi-jazz';
  select count(*)::int into v_embeds_pub from public.site_embeds where site_slug = 'mio-kisaragi-jazz' and published = true;
  select count(*)::int into v_lede from public.site_page_fields
   where site_slug = 'mio-kisaragi-jazz' and page_key = 'about' and field_key = 'profile.lede' and published = true;

  if v_sites <> 1 or v_sched <> 16 or v_sched_pub <> 14
     or v_disco <> 5 or v_disco_pub <> 4
     or v_tracks <> 14 or v_tracks_pub_parent <> 13
     or v_embeds <> 6 or v_embeds_pub <> 5
     or v_lede <> 1 then
    raise exception 'STOP Option A mismatch / TBD blocker: sites=% schedules=%/% disco=%/% tracks=% (on_pub_releases=%) embeds=%/% lede=%. Expected 1 / 16/14 / 5/4 / 14 (13) / 6/5 / 1. Resolve mio-sched-2026-09-01 date=null vs schedules.date NOT NULL, then re-run.',
      v_sites, v_sched, v_sched_pub, v_disco, v_disco_pub, v_tracks, v_tracks_pub_parent, v_embeds, v_embeds_pub, v_lede;
  end if;
end $$;

commit;

-- #############################################################################
-- C) post-write SELECT-only確認（成功時の期待件数）
-- #############################################################################

select * from (
  select 'sites'::text as bucket, count(*)::int as n, 1::int as expect from public.sites where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'schedules', count(*)::int, 16 from public.schedules where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'schedules_published', count(*)::int, 14 from public.schedules where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'schedules_unpublished_draft_or_pending', count(*)::int, 2 from public.schedules where site_slug = 'mio-kisaragi-jazz' and published = false
  union all
  select 'discography', count(*)::int, 5 from public.discography where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography_published', count(*)::int, 4 from public.discography where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'discography_tracks', count(*)::int, 14 from public.discography_tracks where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography_tracks_on_published_releases', count(*)::int, 13
    from public.discography_tracks t
    join public.discography d on d.legacy_id = t.discography_legacy_id and d.site_slug = t.site_slug
   where t.site_slug = 'mio-kisaragi-jazz' and d.published = true
  union all
  select 'site_embeds', count(*)::int, 6 from public.site_embeds where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'site_embeds_published', count(*)::int, 5 from public.site_embeds where site_slug = 'mio-kisaragi-jazz' and published = true
  union all
  select 'about_profile_lede_published', count(*)::int, 1 from public.site_page_fields
   where site_slug = 'mio-kisaragi-jazz' and page_key = 'about' and field_key = 'profile.lede' and published = true
) s;

select 'gosaki_schedules_published_unchanged_check' as bucket, count(*)::int as n
  from public.schedules where site_slug = 'gosaki-piano' and published = true;

-- #############################################################################
-- D) 限定 rollback SQL（別transaction · 明示承認後のみ）
--    Scoped by site_slug + seed legacy prefixes. No table wipe. No other sites.
-- #############################################################################

begin;

delete from public.discography_tracks
 where site_slug = 'mio-kisaragi-jazz'
   and discography_legacy_id like 'mio-disco-%';

delete from public.discography
 where site_slug = 'mio-kisaragi-jazz'
   and legacy_id like 'mio-disco-%';

delete from public.site_embeds
 where site_slug = 'mio-kisaragi-jazz'
   and provider = 'youtube'
   and legacy_item_id like 'mio-yt-%';

delete from public.site_page_fields
 where site_slug = 'mio-kisaragi-jazz'
   and page_key = 'about'
   and field_key = 'profile.lede';

delete from public.schedules
 where site_slug = 'mio-kisaragi-jazz'
   and legacy_id like 'mio-sched-%';

delete from public.sites
 where site_slug = 'mio-kisaragi-jazz';

do $$
declare
  v_left int;
begin
  select (
    (select count(*) from public.schedules where site_slug = 'mio-kisaragi-jazz') +
    (select count(*) from public.discography where site_slug = 'mio-kisaragi-jazz') +
    (select count(*) from public.discography_tracks where site_slug = 'mio-kisaragi-jazz') +
    (select count(*) from public.site_embeds where site_slug = 'mio-kisaragi-jazz') +
    (select count(*) from public.site_page_fields where site_slug = 'mio-kisaragi-jazz') +
    (select count(*) from public.sites where site_slug = 'mio-kisaragi-jazz')
  )::int into v_left;
  if v_left <> 0 then
    raise exception 'STOP rollback incomplete: % mio-kisaragi-jazz rows remain', v_left;
  end if;
end $$;

commit;

-- #############################################################################
-- E) rollback後 SELECT-only確認（期待: 全0）
-- #############################################################################

select * from (
  select 'sites'::text as bucket, count(*)::int as n from public.sites where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'schedules', count(*)::int from public.schedules where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography', count(*)::int from public.discography where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'discography_tracks', count(*)::int from public.discography_tracks where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'site_embeds', count(*)::int from public.site_embeds where site_slug = 'mio-kisaragi-jazz'
  union all
  select 'site_page_fields', count(*)::int from public.site_page_fields where site_slug = 'mio-kisaragi-jazz'
) s;

select 'gosaki_schedules_published' as bucket, count(*)::int as n
  from public.schedules where site_slug = 'gosaki-piano' and published = true;
