import { formatAdminCmsTemplateSection } from "./admin-cms-template.mjs";
import { formatSiteProfileSection } from "./site-profile-loader.mjs";

/**
 * CONVERSION_REPORT.md generator (Phase 2-B / 2-C / 2-E).
 */

function listSection(title, items, formatter) {
  const lines = [`## ${title}`, ""];
  if (!items.length) {
    lines.push("_なし_", "");
    return lines;
  }
  for (const item of items) {
    lines.push(formatter(item));
  }
  lines.push("");
  return lines;
}

function countSeoMissingItems(seoMissingFields) {
  let total = 0;
  for (const row of seoMissingFields) {
    total += row.missing?.length ?? 0;
  }
  return total;
}

/**
 * @param {object} params
 */
export function formatConversionReport({
  inputDir,
  generatedAt,
  outputDir,
  pages,
  cssFiles,
  cssCopiedTo,
  jsCopied,
  jsAnalysis,
  imagesCopied,
  missingAssets,
  forms,
  iframes,
  externalJs,
  inlineScripts,
  externalCss,
  manualReview,
  trailingSlash,
  seoByPage = [],
  seoAssetsCopied = [],
  seoMissingFields = [],
  headerNavActive = true,
  baseUrl = null,
  domainReviewPages = [],
  mainWrapperApplied = true,
  totalPageCount = null,
  scheduleMonthPages = [],
  scheduleIndexGenerated = false,
  headerMonthlyLinksExcluded = false,
  monthlyLinksExcludedFromHeader = 0,
  sourceHtmlCount = null,
  structureVerification = null,
  buildVerification = null,
  fixtureLabel = "gosaki-static-site",
  seoPublishReadiness = null,
  adminCmsSummary = null,
  siteProfileSummary = null,
}) {
  const baseUrlApplied = Boolean(baseUrl);
  const pageCount = totalPageCount ?? pages.length;
  const htmlCount = sourceHtmlCount ?? pages.length;
  const seoMissingItemCount = countSeoMissingItems(seoMissingFields);
  const buildRan = Boolean(buildVerification);
  const buildOk = buildVerification?.buildSuccess ?? false;

  const lines = [
    "# Conversion Report",
    "",
    "Generated by static-to-astro (Phase 2-F).",
    "",
    "## 実サイト検証サマリー",
    "",
    `- **検証フィクスチャ:** \`${fixtureLabel}\`（実サイト由来静的 HTML）`,
    `- **入力ディレクトリ:** \`${inputDir}\``,
    `- **出力ディレクトリ:** \`${outputDir}\``,
    `- **baseUrl:** ${baseUrlApplied ? `\`${baseUrl}\`` : "_(未指定)_"}`,
    `- **生成日時:** ${generatedAt}`,
    `- **検出 HTML 数:** ${htmlCount} file(s)`,
    `- **生成 Astro ページ数:** ${pageCount}（ソース ${pages.length}${scheduleIndexGenerated ? " + Schedule 一覧 1" : ""}）`,
    `- **\`npm run build\`:** ${buildRan ? (buildOk ? "**成功**" : "**失敗** — ログは下記 Build verification") : "_未実行（convert 後に手動で build、または `--verify-build` を使用）_"}`,
    `- **欠損アセット:** ${missingAssets.length}`,
    `- **フォーム:** ${forms.length}`,
    `- **iframe:** ${iframes.length}`,
    `- **外部 JS:** ${externalJs.length}`,
    `- **インライン script:** ${inlineScripts.length}`,
    `- **SEO 欠損項目数（全ページ合計）:** ${seoMissingItemCount}（${seoMissingFields.length} ページに欠損あり）`,
    "",
  ];

  if (structureVerification) {
    lines.push(
      "### 構造チェック（生成直後）",
      "",
      `- **BaseLayout \`<main><slot /></main>\`:** ${structureVerification.baseLayoutHasMainWrapper ? "yes" : "**no**"}`,
      `- **Header Schedule → \`/schedule/\`:** ${structureVerification.headerScheduleLinkToHub ? "yes" : "no"}`,
      `- **Header に月別ラベル（2026.xx）:** ${structureVerification.headerHasMonthlyNavLabels ? "**yes（要確認）**" : "no（除外済み）"}`,
      `- **\`scheduleNavActive()\` in Header:** ${structureVerification.scheduleNavActiveInHeader ? "yes" : "no"}`,
      `- **\`src/pages/schedule/index.astro\`:** ${structureVerification.scheduleIndexExists ? "yes" : "no"}`,
      `- **\`dist/schedule/index.html\`（build 後）:** ${buildVerification?.distScheduleIndexExists ? "yes" : buildRan ? "no" : "_build 未実行_"}`,
      `- **\`public/robots.txt\`:** ${(buildVerification ? buildVerification.robotsTxtInPublic : seoPublishReadiness?.robotsTxtGenerated) ? "yes" : "no"}`,
      `- **sitemap XML（build 後 dist）:** ${(buildVerification?.sitemapFiles?.length ?? 0) ? buildVerification.sitemapFiles.map((f) => `\`${f}\``).join(", ") : buildRan ? "none" : "_build 未実行_"}`,
      "",
    );
  }

  if (seoPublishReadiness) {
    lines.push("## SEO publish readiness", "");
    lines.push(
      `- **baseUrl specified:** ${seoPublishReadiness.baseUrlApplied ? "yes" : "no"}`,
      `- **baseUrl value:** ${seoPublishReadiness.baseUrl ? `\`${seoPublishReadiness.baseUrl}\`` : "—"}`,
      `- **astro.config.mjs \`site\`:** ${seoPublishReadiness.astroSiteConfigured ? "set" : "omitted"}`,
      `- **trailingSlash:** \`${seoPublishReadiness.trailingSlash}\``,
      `- **robots.txt generated:** ${seoPublishReadiness.robotsTxtGenerated ? "yes — `public/robots.txt`" : "no"}`,
      `- **robots.txt policy:** ${seoPublishReadiness.robotsTxtPolicy}`,
      `- **robots.txt Sitemap URL:** ${seoPublishReadiness.robotsTxtSitemapUrl ? `\`${seoPublishReadiness.robotsTxtSitemapUrl}\`` : "—"}`,
      `- **@astrojs/sitemap integration:** ${seoPublishReadiness.sitemapIntegrationEnabled ? "yes" : "no"}`,
      `- **sitemap built on \`npm run build\`:** ${seoPublishReadiness.sitemapBuilt ? "yes" : buildRan ? "no" : "_not verified_"}`,
      seoPublishReadiness.sitemapBuildFiles?.length
        ? `- **sitemap files in dist:** ${seoPublishReadiness.sitemapBuildFiles.map((f) => `\`${f}\``).join(", ")}`
        : "",
      `- **sitemap requirements:** ${seoPublishReadiness.sitemapRequirement}`,
      `- **canonical / og:url / og:image baseUrl normalization:** ${seoPublishReadiness.canonicalNormalization}`,
      "",
      "### SEO publish manual checks",
      "",
      "- Confirm production domain matches `--base-url`.",
      "- Confirm no `noindex` remains on pages intended for indexing.",
      "- Confirm `robots.txt` Sitemap URL is correct for production.",
      "- After `npm run build`, confirm sitemap XML exists under `dist/` (e.g. `sitemap-index.xml`).",
      "- After production deploy, submit sitemap in Google Search Console.",
      "",
    );
  }

  lines.push("## Summary", "");
  lines.push(
    `- **Source directory:** \`${inputDir}\``,
    `- **Output directory:** \`${outputDir}\``,
    `- **Generated at:** ${generatedAt}`,
    `- **Astro trailingSlash:** \`${trailingSlash}\``,
    `- **Pages generated:** ${pageCount}`,
    "",
  );

  lines.push("## Layout / DOM structure", "");
  lines.push(
    "- **BaseLayout 復元:** `<Header />` → `<main><slot /></main>` → `<Footer />`",
    "- **理由:** `extractMainHtml()` はソースの `<main>` **内側のみ**を抽出するため、レイアウトで `<main>` を再付与しないと `main { max-width; margin: auto; padding }` が効かず本文が横幅いっぱいになる。",
    mainWrapperApplied
      ? "- **CSS 検出:** 統合 CSS に `main { max-width: ... }` あり — ラッパー適用は必須。"
      : "- **CSS 検出:** `main { max-width }` は未検出だが、セマンティック `<main>` は常に付与。",
    "- **本文幅:** 中央寄せ・最大幅は親 `<main>` 経由で復元（gosaki: `--width-content` 1000px）。",
    "- **今後の課題（未実装）:** ソース `<main>` の `class` / `id` / `data-*` / `aria-*` の保持。gosaki フィクスチャは属性なしの `<main>` のみ。必要な案件では BaseLayout の `<main>` に属性をマージする拡張が必要。",
    "",
  );

  lines.push("## Schedule navigation", "");
  lines.push(
    `- **schedule-YYYY-MM.html 検出:** ${scheduleMonthPages.length} file(s)`,
    `- **Schedule 一覧 (\`/schedule/\`):** ${scheduleIndexGenerated ? "yes — `src/pages/schedule/index.astro`" : "no"}`,
    `- **Header 月別リンク除外:** ${headerMonthlyLinksExcluded ? `yes（${monthlyLinksExcludedFromHeader} link(s) removed）` : scheduleMonthPages.length ? "no" : "n/a"}`,
    `- **Header Schedule リンク先:** ${scheduleIndexGenerated ? "`/schedule/`" : "unchanged"}`,
    `- **プルダウン復元:** no（運用優先 — 月が増えても Header は単独リンクのまま）`,
    `- **\`scheduleNavActive()\`:** ${structureVerification?.scheduleNavActiveInHeader ?? scheduleIndexGenerated ? "Header.astro に実装 — `/schedule/` および `/schedule-YYYY-MM/` で Schedule が active" : "n/a"}`,
    "",
  );
  if (scheduleMonthPages.length) {
    lines.push("### Monthly schedule pages（一覧は新しい月順）", "");
    lines.push("| Source HTML | Label | Route |");
    lines.push("| --- | --- | --- |");
    for (const m of scheduleMonthPages) {
      lines.push(`| ${m.sourcePath} | ${m.label} | ${m.route} |`);
    }
    lines.push("");
  }

  lines.push("## baseUrl configuration", "");
  if (baseUrlApplied) {
    lines.push(
      `- **Specified:** yes`,
      `- **Value:** \`${baseUrl}\``,
      `- **canonical policy:** \`{baseUrl}{route}\` — overrides source HTML canonical when --base-url is set`,
      `- **og:url policy:** same as canonical (derived from page route)`,
      `- **og:image policy:** local paths converted to absolute URLs (\`${baseUrl}/images/...\`)`,
      `- **favicon / apple-touch-icon:** site-root relative paths in HTML (copy recorded below)`,
      "",
    );
    if (seoByPage.length) {
      lines.push("### URLs after baseUrl normalization", "");
      lines.push("| Page | route | canonical | og:url | og:image | source canonical |");
      lines.push("| --- | --- | --- | --- | --- | --- |");
      for (const row of seoByPage) {
        const srcCanon = row.canonicalOriginal ? truncate(row.canonicalOriginal, 32) : "—";
        lines.push(
          `| ${row.file} | ${row.route ?? "—"} | ${truncate(row.canonical, 36)} | ${truncate(row.ogUrl, 36)} | ${truncate(row.ogImage, 36)} | ${srcCanon} |`,
        );
      }
      lines.push("");
    }
  } else {
    lines.push(
      `- **Specified:** no`,
      `- **Note:** baseUrl was **not** specified. canonical / og:url / og:image from source HTML are preserved (local og:image stays site-root relative).`,
      `- **Action:** Re-run convert with \`--base-url https://your-domain.com\` before production deploy, or edit generated pages manually.`,
      "",
    );
    if (domainReviewPages.length) {
      lines.push("### Pages needing production domain review", "");
      lines.push("| Page | route | canonical (source) | og:url | og:image |");
      lines.push("| --- | --- | --- | --- | --- |");
      for (const row of domainReviewPages) {
        lines.push(
          `| ${row.file} | ${row.route} | ${truncate(row.canonical, 32)} | ${truncate(row.ogUrl, 32)} | ${truncate(row.ogImage, 32)} |`,
        );
      }
      lines.push("");
    }
  }

  if (missingAssets.length) {
    lines.push("## ⚠️ Missing assets (action required)", "");
    lines.push(
      "The following files are referenced in HTML but were **not found** on disk. They were **not** substituted automatically.",
      "",
    );
    lines.push("| Page | Type | Missing path |");
    lines.push("| --- | --- | --- |");
    for (const m of missingAssets) {
      lines.push(`| ${m.file} | ${m.type} | \`${m.asset}\` |`);
    }
    lines.push("");
  }

  lines.push("## Generated pages", "");
  lines.push("| Source HTML | Astro route | Output |");
  lines.push("| --- | --- | --- |");
  for (const p of pages) {
    lines.push(`| ${p.sourcePath} | ${p.route} | \`src/pages/${p.pagePath}\` |`);
  }
  if (scheduleIndexGenerated) {
    lines.push(`| _(generated)_ | /schedule/ | \`src/pages/schedule/index.astro\` |`);
  }
  lines.push("");

  if (buildVerification) {
    lines.push("## Build verification", "");
    lines.push(
      `- **Command:** \`${buildVerification.buildCommand}\``,
      `- **Result:** ${buildVerification.buildSuccess ? "success" : "**failed**"}`,
      `- **Verified at:** ${buildVerification.verifiedAt}`,
      `- **\`dist/schedule/index.html\`:** ${buildVerification.distScheduleIndexExists ? "exists" : "missing"}`,
      "",
    );
    if (!buildVerification.buildSuccess && buildVerification.buildOutput) {
      lines.push("<details>", "<summary>Build log (tail)</summary>", "", "```", buildVerification.buildOutput.trim(), "```", "", "</details>", "");
    }
  }

  lines.push(...listSection("CSS consolidated", cssFiles, (f) => `- \`${f}\` → \`${cssCopiedTo}\``));

  lines.push("## JavaScript", "");
  lines.push("### Copied to `public/assets/js/`", "");
  if (!jsCopied.length) lines.push("_なし_", "");
  else {
    for (const j of jsCopied) {
      lines.push(`- \`${j.from}\` → \`${j.to}\` (${j.scope})`);
    }
    lines.push("");
  }

  if (jsAnalysis.layoutScripts.length) {
    lines.push("### Loaded from BaseLayout (all pages)", "");
    for (const s of jsAnalysis.layoutScripts) {
      lines.push(`- \`${s.to}\` — ${s.from}`);
    }
    lines.push("");
  }

  if (jsAnalysis.pageSpecificScripts.length) {
    lines.push("### Page-specific JS (not in BaseLayout)", "");
    for (const s of jsAnalysis.pageSpecificScripts) {
      lines.push(`- [${s.file}] \`${s.to}\` — add manually or via page script tag`);
    }
    lines.push("");
  }

  lines.push(...listSection("Images copied to `public/images/`", imagesCopied, (i) => `- \`${i}\``));

  lines.push(...listSection(
    "Forms detected",
    forms,
    (f) => `- [${f.file}] action=\`${f.action || "(none)"}\` method=${f.method || "GET"}`,
  ));

  lines.push(...listSection(
    "Iframes detected",
    iframes,
    (f) => `- [${f.file}] src=\`${(f.src || "").slice(0, 80)}${(f.src || "").length > 80 ? "…" : ""}\``,
  ));

  lines.push(...listSection(
    "External JS (not copied)",
    externalJs,
    (j) => `- [${j.file}] \`${j.src}\``,
  ));

  lines.push(...listSection(
    "Inline scripts (not migrated)",
    inlineScripts,
    (s) => `- [${s.file}] ${s.length} chars — \`${s.preview}…\``,
  ));

  lines.push(...listSection(
    "External CSS / fonts (preserved as link in BaseLayout)",
    externalCss,
    (c) => `- \`${c.href}\`${c.pages ? ` (pages: ${c.pages.join(", ")})` : ""}`,
  ));

  lines.push("## SEO / OGP migration", "");
  lines.push(
    headerNavActive
      ? "- **Header navigation:** `is-current` class applied via `Astro.url.pathname` (trailingSlash-aware)."
      : "- **Header navigation:** active class not applied automatically — see manual review.",
    "",
  );

  if (seoAssetsCopied.length) {
    lines.push("### OGP / favicon assets copied", "");
    for (const a of seoAssetsCopied) {
      lines.push(`- \`${a.from}\` → \`${a.to}\``);
    }
    lines.push("");
  }

  if (seoByPage.length) {
    lines.push("### Per-page SEO", "");
    lines.push("| Page | title | description | canonical | og:image | favicon | lang | missing |");
    lines.push("| --- | --- | --- | --- | --- | --- | --- | --- |");
    for (const row of seoByPage) {
      const miss = row.missing.length ? row.missing.join(", ") : "—";
      lines.push(
        `| ${row.file} | ${truncate(row.title, 40)} | ${truncate(row.description, 36)} | ${truncate(row.canonical, 28)} | ${truncate(row.ogImage, 24)} | ${truncate(row.favicon, 20)} | ${row.lang} | ${miss} |`,
      );
    }
    lines.push("");
    lines.push("#### og:title / og:description", "");
    for (const row of seoByPage) {
      lines.push(`- **${row.file}** — og:title: ${row.ogTitle || "—"}; og:description: ${truncate(row.ogDescription, 60)}`);
    }
    lines.push("");
  }

  if (seoMissingFields.length) {
    lines.push("### Missing SEO fields (not in source HTML)", "");
    for (const row of seoMissingFields) {
      lines.push(`- [${row.file}] ${row.missing.join(", ")}`);
    }
    lines.push("");
  }

  lines.push("### SEO manual checks", "");
  if (baseUrlApplied) {
    lines.push(
      "- Verify `--base-url` matches your production domain.",
      "- Confirm og:image absolute URLs are reachable after deploy.",
      "- Twitter/X card tags beyond `twitter:card` are not migrated yet.",
      "",
    );
  } else {
    lines.push(
      "- **baseUrl not set** — canonical / og:url / og:image require manual production URL verification.",
      "- Re-run with `--base-url https://your-domain.com` to normalize URLs automatically.",
      "- Twitter/X card tags beyond `twitter:card` are not migrated yet.",
      "",
    );
  }

  lines.push("## 手動確認項目", "");
  lines.push(
    "1. **dev サーバー:** `cd output/generated-astro && npm run dev` — **ターミナルに表示された URL** を開く（例: `http://localhost:4321/` や `http://127.0.0.1:4325/`）。古いポートで 404 にならないこと。",
    "2. **ルート確認:**",
    "",
  );
  for (const route of [
    "/",
    "/schedule/",
    "/schedule-2026-07/",
    "/schedule-2026-06/",
    "/schedule-2026-05/",
    "/schedule-2026-04/",
    "/schedule-2026-03/",
    "/about/",
    "/discography/",
    "/contact/",
    "/link/",
  ]) {
    lines.push(`   - \`${route}\` — 404 でないこと`);
  }
  lines.push(
    "",
    "3. **Schedule 一覧:** `/schedule/` に 2026.07〜2026.03 が**新しい順**で並ぶこと。各リンクが月別ページへ遷移すること。",
    "4. **Header:** `2026.07` / `2026.06` 等が横並びで出ないこと。`Schedule` のみで `/schedule/` へ。月別ページ閲覧時も Schedule が active。",
    "5. **レイアウト:** トップ・スケジュールの本文が横幅いっぱいに広がっていない（`main` max-width 効いている）こと。",
    "6. **スマホ表示:** 主要ページを狭い幅で目視確認。",
    "7. **フォーム:** contact の `action` / 送信先を本番用に差し替えること。",
    "8. **iframe / 外部 JS / インライン script:** 本番で許容するか確認。",
    "9. **canonical / og:url / og:image:** 本番ドメインと一致するか確認。",
    "",
  );

  if (siteProfileSummary?.active) {
    lines.push(formatSiteProfileSection(siteProfileSummary));
  }

  if (adminCmsSummary) {
    lines.push(formatAdminCmsTemplateSection(adminCmsSummary));
  } else {
    lines.push(
      "## Admin CMS template",
      "",
      "- **Applied:** no (`--with-admin-cms` not used)",
      "",
    );
  }

  lines.push("## Manual review required", "");
  if (!manualReview.length) {
    lines.push("_特になし（欠損アセット・外部依存を確認してください）_", "");
  } else {
    for (const item of manualReview) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("## Next steps for humans", "");
  lines.push(
    "1. Open `npm run dev` and compare each route with the original static HTML.",
    "2. Fix or add missing assets listed above.",
    "3. Replace contact form `action` with your form backend (Formrun, Netlify Forms, etc.).",
    "4. Verify Google Maps / iframe embeds still load.",
    "5. Confirm external fonts and third-party JS are acceptable for production.",
    "6. Review page-specific JS and inline scripts before go-live.",
    "7. Phase 2-G: visual diff (Playwright), JSON-LD — see `tools/static-to-astro/README.md`.",
    "",
  );

  return lines.join("\n");
}

function truncate(value, max) {
  const s = value ?? "";
  if (!s) return "—";
  return s.length > max ? `${s.slice(0, max)}…` : s;
}
